### PR TITLE
update

### PR DESCRIPTION
**Pull request by DoubleAix**
issue #40 
**Proposed changes**:
- update the version of rasa_nlu from 0.12.0a1 to 0.12.2 (replace old code with new code)
- add defaultdict setting function
- be able to put in dict paths as parameters to the config file
- create a config file example for adding dict paths
- modify files including setup.py, jieba_tokenizer.py and requirements_bare.txt by myselfs

**Status (please check what you already did)**:
- [ ] made PR ready for code review
- [ ] added some tests for the functionality
- [ ] updated the documentation
- [ ] updated the changelog

### CODE REVIEW

**Comment by DoubleAix** [comment]
the config file like this:
image

**Comment by crownpku** [comment]
Hi, @DoubleAix . Let me merge the repo with the newest rasa NLU first, and it will be great if you can send another PR based on that. Thank you!

**Comment by DoubleAix** [comment]
OKOK, I'm just waiting for this reply. I think that updating to the newest version first is reasonable.

**Comment by crownpku** [comment]
Just merged the repo @DoubleAix. Please clone again and make modifications based on it. Thank you!

**Pull request closed without merging**
